// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: grpcgorm/grpcgorm.proto

package grpcgorm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_grpcgorm_grpcgorm_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_grpcgorm_grpcgorm_proto_rawDescGZIP(), []int{1}
}

func (x *PostResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcgorm_grpcgorm_proto_rawDescGZIP(), []int{2}
}

// Represents multiple posts (for GetAll)
type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostResponse        `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcgorm_grpcgorm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_grpcgorm_grpcgorm_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllResponse) GetPosts() []*PostResponse {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_grpcgorm_grpcgorm_proto protoreflect.FileDescriptor

const file_grpcgorm_grpcgorm_proto_rawDesc = "" +
	"\n" +
	"\x17grpcgorm/grpcgorm.proto\x12\bgrpcgorm\"C\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"N\n" +
	"\fPostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\a\n" +
	"\x05Empty\">\n" +
	"\x0eGetAllResponse\x12,\n" +
	"\x05posts\x18\x01 \x03(\v2\x16.grpcgorm.PostResponseR\x05posts2~\n" +
	"\bGRPCGORM\x12=\n" +
	"\x06Create\x12\x1b.grpcgorm.CreatePostRequest\x1a\x16.grpcgorm.PostResponse\x123\n" +
	"\x06GetAll\x12\x0f.grpcgorm.Empty\x1a\x18.grpcgorm.GetAllResponseB\x1cZ\x1agrpcgorm/grpcgorm;grpcgormb\x06proto3"

var (
	file_grpcgorm_grpcgorm_proto_rawDescOnce sync.Once
	file_grpcgorm_grpcgorm_proto_rawDescData []byte
)

func file_grpcgorm_grpcgorm_proto_rawDescGZIP() []byte {
	file_grpcgorm_grpcgorm_proto_rawDescOnce.Do(func() {
		file_grpcgorm_grpcgorm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcgorm_grpcgorm_proto_rawDesc), len(file_grpcgorm_grpcgorm_proto_rawDesc)))
	})
	return file_grpcgorm_grpcgorm_proto_rawDescData
}

var file_grpcgorm_grpcgorm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcgorm_grpcgorm_proto_goTypes = []any{
	(*CreatePostRequest)(nil), // 0: grpcgorm.CreatePostRequest
	(*PostResponse)(nil),      // 1: grpcgorm.PostResponse
	(*Empty)(nil),             // 2: grpcgorm.Empty
	(*GetAllResponse)(nil),    // 3: grpcgorm.GetAllResponse
}
var file_grpcgorm_grpcgorm_proto_depIdxs = []int32{
	1, // 0: grpcgorm.GetAllResponse.posts:type_name -> grpcgorm.PostResponse
	0, // 1: grpcgorm.GRPCGORM.Create:input_type -> grpcgorm.CreatePostRequest
	2, // 2: grpcgorm.GRPCGORM.GetAll:input_type -> grpcgorm.Empty
	1, // 3: grpcgorm.GRPCGORM.Create:output_type -> grpcgorm.PostResponse
	3, // 4: grpcgorm.GRPCGORM.GetAll:output_type -> grpcgorm.GetAllResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpcgorm_grpcgorm_proto_init() }
func file_grpcgorm_grpcgorm_proto_init() {
	if File_grpcgorm_grpcgorm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcgorm_grpcgorm_proto_rawDesc), len(file_grpcgorm_grpcgorm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcgorm_grpcgorm_proto_goTypes,
		DependencyIndexes: file_grpcgorm_grpcgorm_proto_depIdxs,
		MessageInfos:      file_grpcgorm_grpcgorm_proto_msgTypes,
	}.Build()
	File_grpcgorm_grpcgorm_proto = out.File
	file_grpcgorm_grpcgorm_proto_goTypes = nil
	file_grpcgorm_grpcgorm_proto_depIdxs = nil
}
