// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpcgorm/grpcgorm.proto

package grpcgorm

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCGORM_Create_FullMethodName = "/grpcgorm.GRPCGORM/Create"
	GRPCGORM_GetAll_FullMethodName = "/grpcgorm.GRPCGORM/GetAll"
)

// GRPCGORMClient is the client API for GRPCGORM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCGORMClient interface {
	Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type gRPCGORMClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCGORMClient(cc grpc.ClientConnInterface) GRPCGORMClient {
	return &gRPCGORMClient{cc}
}

func (c *gRPCGORMClient) Create(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, GRPCGORM_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCGORMClient) GetAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, GRPCGORM_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCGORMServer is the server API for GRPCGORM service.
// All implementations must embed UnimplementedGRPCGORMServer
// for forward compatibility.
type GRPCGORMServer interface {
	Create(context.Context, *CreatePostRequest) (*PostResponse, error)
	GetAll(context.Context, *Empty) (*GetAllResponse, error)
	mustEmbedUnimplementedGRPCGORMServer()
}

// UnimplementedGRPCGORMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCGORMServer struct{}

func (UnimplementedGRPCGORMServer) Create(context.Context, *CreatePostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedGRPCGORMServer) GetAll(context.Context, *Empty) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedGRPCGORMServer) mustEmbedUnimplementedGRPCGORMServer() {}
func (UnimplementedGRPCGORMServer) testEmbeddedByValue()                  {}

// UnsafeGRPCGORMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCGORMServer will
// result in compilation errors.
type UnsafeGRPCGORMServer interface {
	mustEmbedUnimplementedGRPCGORMServer()
}

func RegisterGRPCGORMServer(s grpc.ServiceRegistrar, srv GRPCGORMServer) {
	// If the following call pancis, it indicates UnimplementedGRPCGORMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCGORM_ServiceDesc, srv)
}

func _GRPCGORM_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCGORMServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCGORM_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCGORMServer).Create(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCGORM_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCGORMServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRPCGORM_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCGORMServer).GetAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCGORM_ServiceDesc is the grpc.ServiceDesc for GRPCGORM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCGORM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcgorm.GRPCGORM",
	HandlerType: (*GRPCGORMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GRPCGORM_Create_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _GRPCGORM_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcgorm/grpcgorm.proto",
}
