// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pkg/proto/chat.proto

package grpcchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_pkg_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *MessageRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *MessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_pkg_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_pkg_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *JoinRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_pkg_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *ChatMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_chat_proto protoreflect.FileDescriptor

const file_pkg_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/chat.proto\x12\x04chat\"X\n" +
	"\x0eMessageRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"'\n" +
	"\x0fMessageResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"S\n" +
	"\vJoinRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"@\n" +
	"\vChatMessage\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb4\x01\n" +
	"\x04CHAT\x12:\n" +
	"\vPrivateSend\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\x126\n" +
	"\fJoinChatRoom\x12\x11.chat.JoinRequest\x1a\x11.chat.ChatMessage0\x01\x128\n" +
	"\fBidiChatRoom\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x010\x01B\x19Z\x17grpcchat/proto/grpcchatb\x06proto3"

var (
	file_pkg_proto_chat_proto_rawDescOnce sync.Once
	file_pkg_proto_chat_proto_rawDescData []byte
)

func file_pkg_proto_chat_proto_rawDescGZIP() []byte {
	file_pkg_proto_chat_proto_rawDescOnce.Do(func() {
		file_pkg_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_chat_proto_rawDesc), len(file_pkg_proto_chat_proto_rawDesc)))
	})
	return file_pkg_proto_chat_proto_rawDescData
}

var file_pkg_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_chat_proto_goTypes = []any{
	(*MessageRequest)(nil),  // 0: chat.MessageRequest
	(*MessageResponse)(nil), // 1: chat.MessageResponse
	(*JoinRequest)(nil),     // 2: chat.JoinRequest
	(*ChatMessage)(nil),     // 3: chat.ChatMessage
}
var file_pkg_proto_chat_proto_depIdxs = []int32{
	0, // 0: chat.CHAT.PrivateSend:input_type -> chat.MessageRequest
	2, // 1: chat.CHAT.JoinChatRoom:input_type -> chat.JoinRequest
	3, // 2: chat.CHAT.BidiChatRoom:input_type -> chat.ChatMessage
	1, // 3: chat.CHAT.PrivateSend:output_type -> chat.MessageResponse
	3, // 4: chat.CHAT.JoinChatRoom:output_type -> chat.ChatMessage
	3, // 5: chat.CHAT.BidiChatRoom:output_type -> chat.ChatMessage
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_chat_proto_init() }
func file_pkg_proto_chat_proto_init() {
	if File_pkg_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_chat_proto_rawDesc), len(file_pkg_proto_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_chat_proto_goTypes,
		DependencyIndexes: file_pkg_proto_chat_proto_depIdxs,
		MessageInfos:      file_pkg_proto_chat_proto_msgTypes,
	}.Build()
	File_pkg_proto_chat_proto = out.File
	file_pkg_proto_chat_proto_goTypes = nil
	file_pkg_proto_chat_proto_depIdxs = nil
}
